// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata/frontgate/default.proto

package pbfrontgate // import "openpitrix.io/metadata/pkg/pb/frontgate"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Default struct {
	FrontgateServicePort *int32   `protobuf:"varint,1,opt,name=FrontgateServicePort,def=9111" json:"FrontgateServicePort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Default) Reset()         { *m = Default{} }
func (m *Default) String() string { return proto.CompactTextString(m) }
func (*Default) ProtoMessage()    {}
func (*Default) Descriptor() ([]byte, []int) {
	return fileDescriptor_default_713521f2849dce2f, []int{0}
}
func (m *Default) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Default.Unmarshal(m, b)
}
func (m *Default) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Default.Marshal(b, m, deterministic)
}
func (dst *Default) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Default.Merge(dst, src)
}
func (m *Default) XXX_Size() int {
	return xxx_messageInfo_Default.Size(m)
}
func (m *Default) XXX_DiscardUnknown() {
	xxx_messageInfo_Default.DiscardUnknown(m)
}

var xxx_messageInfo_Default proto.InternalMessageInfo

const Default_Default_FrontgateServicePort int32 = 9111

func (m *Default) GetFrontgateServicePort() int32 {
	if m != nil && m.FrontgateServicePort != nil {
		return *m.FrontgateServicePort
	}
	return Default_Default_FrontgateServicePort
}

func init() {
	proto.RegisterType((*Default)(nil), "metadata.frontgate.Default")
}

func init() {
	proto.RegisterFile("metadata/frontgate/default.proto", fileDescriptor_default_713521f2849dce2f)
}

var fileDescriptor_default_713521f2849dce2f = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0x4d, 0x2d, 0x49,
	0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x4f, 0x2b, 0xca, 0xcf, 0x2b, 0x49, 0x4f, 0x2c, 0x49, 0xd5, 0x4f,
	0x49, 0x4d, 0x4b, 0x2c, 0xcd, 0x29, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x82, 0xa9,
	0xd0, 0x83, 0xab, 0x50, 0x72, 0xe6, 0x62, 0x77, 0x81, 0x28, 0x12, 0xb2, 0xe0, 0x12, 0x71, 0x83,
	0x89, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x06, 0xe4, 0x17, 0x95, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0xb0, 0x5a, 0xb1, 0x58, 0x1a, 0x1a, 0x1a, 0x06, 0x61, 0x55, 0xe1, 0x64, 0x1a, 0x65, 0x9c,
	0x5f, 0x90, 0x9a, 0x57, 0x90, 0x59, 0x52, 0x94, 0x59, 0xa1, 0x97, 0x99, 0xaf, 0x0f, 0x77, 0x4a,
	0x41, 0x76, 0xba, 0x7e, 0x41, 0x12, 0xc2, 0x45, 0xd6, 0x05, 0x49, 0x70, 0x36, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x9e, 0xc3, 0xdc, 0x97, 0xb2, 0x00, 0x00, 0x00,
}
